name: wiiqare
description: A new Flutter project.



publish_to: 'none' 











version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  intl_phone_number_input: ^0.6.0
  cached_network_image: ^2.4.1
  font_awesome_flutter: ^8.10.0
  flutter_svg: ^0.18.1
  flutter_launcher_icons: ^0.8.1
  google_fonts: ^1.1.1
  introduction_screen: ^1.0.9
  flutter_rounded_progress_bar: ^0.1.2
  qr_code_scanner: ^0.3.0
flutter:

  uses-material-design: true
  assets:
    - assets/images/

  # fonts:
  #   - family: Ubuntu
  #     fonts:
  #       - asset: assets/fonts/Ubuntu-Regular.ttf
