export 'wikiText.dart';
export 'wikiButtom.dart';
export 'grandTitle.dart';
export 'singleTitle.dart';
export 'logoWiiQare.dart';
export 'wiIQareCenterLogoWithIcons.dart';
export 'singleText20pixel.dart';
//export 'welcomWhishWithButtomLogin.dart';
// export 'welcomItemsButtom.dart';
// export 'wikiOffres.dart';
export 'wikiAppBar.dart';
export '../ui/qrCodeViewsScanncer.dart';
//export 'wikiItemHome.dart';
export 'hitoriqueItem.dart';
export 'wikiObjectifItemBar.dart';
export 'stepCreateObjectif.dart';
export 'mapButtom.dart';
export 'rechargerTelecomButtom.dart';
